CREATE DATABASE `pokeapi`;

CREATE TABLE pokeapi.pokemons(
id INT(8) AUTO_INCREMENT PRIMARY KEY NOT NULL,
name VARCHAR(50) NOT NULL, 
typeId TINYINT(3) NOT NULL,
FOREIGN KEY (typeID) REFERENCES types(id)
);

CREATE TABLE pokeapi.types (
id TINYINT(3) NOT NULL PRIMARY KEY AUTO_INCREMENT,
type1 VARCHAR(50) NOT NULL,
type2 VARCHAR(50)
);

SELECT * FROM pokemons;
